version: "3.8"

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: password
      DB_NAME: klinik_laktasi
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: klinik_laktasi
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
