name: PHP Syntax Check

on:
  push:
    branches: [ "master" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check PHP syntax
        run: |
          find . -name "*.php" -not -path "./vendor/*" -exec php -l {} \;